# Generated by Django 4.0.8 on 2022-11-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_display_name_alter_category_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
