# Generated by Django 4.1.1 on 2022-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_store_shoplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
