# Generated by Django 4.1.1 on 2022-09-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shoplist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.item'),
        ),
    ]
