# Generated by Django 4.0.8 on 2022-11-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_name_alter_item_name_alter_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
