# Generated by Django 4.0.8 on 2022-11-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_private_store_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='private',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='private',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
