# Generated by Django 4.0.8 on 2022-11-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_private_alter_store_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
